### ISSUE TITLE
check for palindromes without the use of building an extra string

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/reverse-string#2]
There actually is a way to print the given string in reverse and check for palindromes without the need to store each letter in a new string  😏 

Think about how you, as a Human would approach this problem?

**Comment by nsofiia** [comment]
@incredibleLeitman 
as a human, I take a word, then I reproduce the word in reverse order letter by letter, having in mind the original word given.
This is how I will know if it sounds the same.

**Comment by incredibleLeitman** [comment]
Ok this is one approach, that works very well... and your implemented solution follows basically this pattern:
check if the whole word in reverse matches the given word.

But there is another approach:
If, to be a palindrome, every letter has to be the same, 
this means on the other hand that if one of the letter does not match the letter on the other side the word cannot be a palindrome 😏 
Can you try put that in code?

**Comment by nsofiia** [comment]
I want to know all the ways, can you show me how else it could have been done?

been working on comparing first indexes with (-indexes), but no luck yet :)

**Comment by nsofiia** [comment]
<img width="444" alt="Screen Shot 2022-11-24 at 6 21 38 PM" src="https://user-images.githubusercontent.com/88280676/203877722-4fcd6aeb-9a27-4161-a4cf-b135118a75be.png">

trying to compare index values, throws an error that index is out of range.

<img width="751" alt="Screen Shot 2022-11-24 at 6 21 28 PM" src="https://user-images.githubusercontent.com/88280676/203877835-43c6c0bf-c1f4-42b2-b9ed-50259e6ac726.png">

**Comment by incredibleLeitman** [comment]
comparing indices is a promising direction 😄 👍 
But an index can never be negative!
An Index have always be within the bounds of the element, starting from 0 to length - 1

**Comment by nsofiia** [comment]
what is another method of reversing a string?

**Comment by incredibleLeitman** [comment]
any loop will do... 

do while, while, for... you even could use a foreach with char but this will make it harder to use access the index of the string.

Speaking of, because you are planing on using the index a for loop would be fitting because this kind of loop already utilizes the index

**Comment by incredibleLeitman** [comment]
Yeah you almost did it :D 👍 🎉 

Your implementation is very good! Amazing work especially that you come up with this solution by yourself!
```
if (initialInput[index] == initialInput[actualIndex])
{
  actualIndex++;
  palindromeCount++;
}

if (palindromeCount == initialInput.Length)
{
  Console.WriteLine("\nPalindrome");
}
```

But there is even more improvement possible :D
You don't really need the extra "actualIndex" and increase it seperately... you can use "index" and substract it from the Length of the string to get the other side:
```
if (initialInput[index] == initialInput[initialInput.Length - index - 1])
```

Additionally instead of checking if all chars are equal, you could go the other way and say it cannot be a palindrome if one letter is not equal:
```
Console.WriteLine("Hello, I'll reverse anything you say: ");
string initialInput = Console.ReadLine().ToLower();

bool isPalindrome = true; // assume this is a palindrome at first
for (int index = initialInput.Length - 1; index >= 0; index--)
{
  Console.Write(initialInput[index]);
  if (initialInput[index] != initialInput[initialInput.Length - index - 1])
  {
    isPalindrome = false; // if one letter is not equal -> this cannot be a palindrome
  }
}

if (isPalindrome)
{
  Console.WriteLine("\nThis is a Palindrome");
}
Console.ReadLine();
``` 

Additional optimizations could be, to only even check the letter if isPalindrome is still true, because once it was false it cannot be true anymore, or to only check until the middle of the string because if the first half matches the other, the string is a palindrome.
